application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "4d 5h"

handlers:
- url: (.*)/
  static_files: public\1/index.html
  upload: public/.*/index\.html

- url: /(.+)
  static_files: public/\1
  upload: public/(.*)

